### ISSUE TITLE
关于“登陆”字样的问题

### ISSUE THREAD

**Issue by Alvis-is-coding** [xidian-rs/Ruisi_Ios#12]
感谢开发者开发的IOS版本，有一件事很早之前就想反馈了。就是“登录”的问题，我是软件工程专业的学生，我在上软件测试课的时候，第一节课老师就跟我们说了软件开发的“登录”的“录”是录入的“录”，而不是“着陆”的“陆”（还说谁要把“登录”写成“登陆”，直接不及格T_T）。其实查看各大网站、软件的登录界面都能发现这点，希望开发者能注意一下。

**Comment by freedom10086** [comment]
语文不及格，感谢提醒。。
